<?php
get_header();
?>
<div id="primary" class="site-content cma-content">
    <div class="cma-main">
        <div class="cma-wrapper">
            <div id="content" role="main" class="entry-content">
                <header class="entry-header">
                    <h1 class="entry-title">
                        <?php _e('Tất cả câu hỏi', 'cm-answers'); ?>
                    </h1>
                </header>
                <div style="clear:both;height:15px;"></div>

                <?php
                $currentSort = !empty($_GET['sort']) ? $_GET['sort'] : 'newest';
                if (!ctype_alnum($currentSort)) $currentSort = 'newest';
                ?>
                <ul class="cma-thread-orderby">
                    <li<?php if( $currentSort == 'newest' ): ?> class="cma-current-sort"<?php endif; ?>><a href="<?php echo esc_attr(add_query_arg(array('sort' => 'newest'), get_pagenum_link(0))); ?>"><?php _e('Mới nhất', 'cm-answers'); ?></a></li>
                    <li<?php if( $currentSort == 'hottest' ): ?> class="cma-current-sort"<?php endif; ?>><a href="<?php echo esc_attr(add_query_arg(array('sort' => 'hottest'), get_pagenum_link(0))); ?>"><?php _e('Hot nhất', 'cm-answers'); ?></a></li>
                    <?php if( CMA_AnswerThread::isRatingAllowed() ): ?><li<?php if( $currentSort == 'votes' ): ?> class="cma-current-sort"<?php endif; ?>><a href="<?php echo esc_attr(add_query_arg(array('sort' => 'votes'), get_pagenum_link(0))); ?>"><?php _e('Votes nhiều nhất', 'cm-answers'); ?></a></li><?php endif; ?>
                    <li<?php if( $currentSort == 'views' ): ?> class="cma-current-sort"<?php endif; ?>><a href="<?php echo esc_attr(add_query_arg(array('sort' => 'views'), get_pagenum_link(0))); ?>"><?php _e('Xem nhiều nhất', 'cm-answers'); ?></a></li>
                </ul>
                <div class="cma-clear"></div>
                <div class="detail-inner masonry-container">
                <?php
                do_action('CMA_show_messages');
                if( have_posts() ):
                    ?>
                        <?php
                        while(have_posts()):
                            the_post();
                            $thread = CMA_AnswerThread::getInstance($post->ID);
                            ?>
                            <div class="col-md-4 box topic">
                            <div class="article">
                            <div style="<?php echo $style; ?>margin-left:10px;width:100%;float:left;margin-bottom:10px">
                            <div class="StatBox AnswersBox HasAnswersBox">
                            <span>Bình luận</span>
                            <?php
                            $numberOfAnswers = $thread->getNumberOfAnswers();
                            echo $numberOfAnswers; ?>
                            </div>
                            <div class="StatBox ViewsBox">
                            <span>Xem</span>
                            <?php
                                $views = $thread->getViews();
                                echo $views;
                            ?>
                            </div>
                            <?php if( CMA_AnswerThread::isRatingAllowed() ): ?>
                            <div class="StatBox ViewsBox" style="background: #73a550;color: #FFF;">
                            <span>Thích</span>
                            <?php
                                $votes = $thread->getVotes();
                                                echo $votes;
                            ?>
                            </div>
                            <?php endif; ?>
                            <div class="ItemContent Discussion">
                                <a style="color:#282828" href="<?php echo esc_attr(get_permalink(get_the_ID())); ?>"><?php echo $thread->getTitle(); ?></a>
                            <div class="Meta">
                            <span class="Announcement"><?php echo $thread->getLastPosterName();?></span>
                            <span class="LastCommentDate"><?php printf(__('updated %s by %s', 'cm-answers'),
                                    	CMA_AnswerThread::renderDaysAgo($thread->getUnixUpdated()), $thread->getLastPosterName()); ?></span>
                            </div>
                            </div>
                            </div>
                            </div>
                            </div>
                            <?php
                        endwhile;
                        ?>
                        </div>
                    <div class="cma-pagination"><?php
                        echo paginate_links(array(
                            'base'     => trailingslashit(get_post_type_archive_link(CMA_AnswerThread::POST_TYPE)) . '%_%',
                            'format'   => 'page/%#%/',
                            'current'  => max(1, get_query_var('paged')),
                            'total'    => $GLOBALS['wp_query']->max_num_pages,
                            'add_args' => $currentSort != 'newest' ? array('sort' => $currentSort) : array()
                        ));
                        ?></div><?php
                endif;
                ?>
                <div class="cma-form-container">
                    <?php if( is_user_logged_in() ): ?>
                        <div style="clear:both;height:40px;"></div>
                        <form method="post" class="cma-thread-add" id="cma-thread-add">
                            <input type="hidden" name="cma-action" value="add" />
                            <input type="hidden" name="nonce" value="<?php echo esc_attr(wp_create_nonce('cma_question')); ?>" />
                            <h3><?php _e('Ask a Question', 'cm-answers'); ?></h3>
                            <div style="clear:both;height:10px;"></div>
                            <ul class="cma-form-notes">
                                <li><?php _e('Allow markup', 'cm-answers'); ?>: &lt;strong&gt;, &lt;em&gt;, &lt;a&gt;</li>
                                <li><?php _e('Wrap your code using', 'cm-answers'); ?> &lt;pre&gt;&lt;/pre&gt;</li>
                            </ul>
                            <input type="text" size="50" name="thread_title" placeholder="<?php _e('Question Title', 'cm-answers'); ?>" /><br />
                            <textarea name="thread_comment" cols="50" rows="3" placeholder="<?php _e('What is your Question about?', 'cm-answers'); ?>"></textarea><br />
                            <div style="clear:both;height:5px;"></div>
                            <label>
                                <input name="thread_notify" type="checkbox" value="1"/>
                                <?php _e('Notify me of follow', 'cm-answers'); ?></label><br />
                            <div style="clear:both;height:10px;"></div>
                            <input type="submit" value="<?php _e('Add Question', 'cm-answers'); ?>" />
                        </form>
                        <?php
                    else:
                        do_action('CMA_login_form');
                    endif;
                    ?>
                </div>
            </div>
            <span class="cma_poweredby">
            	<a href="http://cminds.com/" target="_blank" class="cma_poweredbylink">CreativeMinds WordPress</a>
            	<a href="https://www.cminds.com/store/" target="_blank" class="cma_poweredbylink">Plugin Store</a>
            	<a href="https://www.cminds.com/store/answers/" target="_blank" class="cma_poweredbylink">CM Answers</a>
            </span>

        </div>
        <?php if( CMA_AnswerThread::isSidebarEnabled() && is_active_sidebar('cm-answers-sidebar') ): ?>
            <?php
            $maxWidth = CMA_AnswerThread::getSidebarMaxWidth() > 0 ? 'style="max-width:' . $maxWidth . 'px"' : '';
            ?>
            <div id="secondary" role="complementary" class="widget-area cma-sidebar" <?php echo $maxWidth; ?>>
                <?php dynamic_sidebar('cm-answers-sidebar'); ?>
            </div>
        <?php endif; ?>
    </div>
</div>
<?php
get_footer();
